(function (global) {
    "use strict";

    const Utils = global.OptionsAssistantUtils;
    const Context = global.OptionsMarketContext;

    function evaluate(args, settings, options) {
        const config = settings || Utils.DEFAULT_SETTINGS;
        const marketContext = args && args.marketContext ? args.marketContext : {};
        const overallSignal = args && args.overallSignal ? args.overallSignal : Utils.createEmptyOverallSignal();
        const trendAnalysis = args && args.trendAnalysis ? args.trendAnalysis : Utils.createEmptyTrendAnalysis();
        const gapPrediction = args && args.gapPrediction ? args.gapPrediction : Utils.createEmptyGapPrediction();
        const structureAnalysis = args && args.structureAnalysis ? args.structureAnalysis : Utils.createEmptyStructureAnalysis();
        const newsSentiment = args && args.newsSentiment ? args.newsSentiment : Utils.createEmptyNewsSentiment();
        const values = marketContext.aggregateValues || Utils.createEmptyValues();
        const levels = marketContext.supportResistance || Utils.createEmptySupportResistance();
        const reasoning = [];
        const warnings = [];
        const score = {
            bullish: 0,
            bearish: 0,
            sideways: 14
        };
        let contributors = 0;

        const closeStrength = evaluateCloseStrength(values);
        const lastHourMomentum = calculateLastHourMomentum(marketContext.snapshotsByTab || {});

        applyTrendAlignment(score, trendAnalysis, closeStrength, reasoning);
        contributors += 1;

        applyClosePosition(score, closeStrength, reasoning);
        contributors += closeStrength.available ? 1 : 0;

        if (Number.isFinite(lastHourMomentum)) {
            contributors += 1;
            if (lastHourMomentum >= 0.18) {
                score.bullish += 10;
                reasoning.push("Last-hour momentum stayed positive into the close.");
            } else if (lastHourMomentum <= -0.18) {
                score.bearish += 10;
                reasoning.push("Last-hour momentum stayed negative into the close.");
            } else {
                score.sideways += 6;
                reasoning.push("Last-hour momentum faded into the close.");
            }
        }

        if (Number.isFinite(values.pcr)) {
            contributors += 1;
            if (values.pcr >= config.bullishPcrThreshold) {
                score.bullish += 8;
                reasoning.push("PCR still leans supportive for bulls.");
            } else if (values.pcr <= config.bearishPcrThreshold) {
                score.bearish += 8;
                reasoning.push("PCR still leans supportive for bears.");
            } else {
                score.sideways += 4;
            }
        }

        if (Number.isFinite(values.vix)) {
            contributors += 1;
            if (values.vix >= config.highVixThreshold) {
                warnings.push("VIX is elevated, so overnight conviction is reduced.");
            } else if (values.vix <= config.elevatedVixThreshold) {
                reasoning.push("VIX is controlled enough for directional follow-through.");
            }
        }

        if (Number.isFinite(values.maxPain) && Number.isFinite(values.spotPrice)) {
            contributors += 1;
            if (values.maxPain > values.spotPrice) {
                score.bullish += 7;
                reasoning.push("Max pain above spot suggests bullish drift.");
            } else if (values.maxPain < values.spotPrice) {
                score.bearish += 7;
                reasoning.push("Max pain below spot suggests bearish drift.");
            }
        }

        applyStructure(score, structureAnalysis, reasoning);
        contributors += 1;

        applyGapRead(score, gapPrediction, reasoning);
        contributors += 1;

        if (newsSentiment.sentiment === "BULLISH") {
            contributors += 1;
            score.bullish += Math.max(4, Math.round((newsSentiment.confidence || 0) / 18));
            reasoning.push("News sentiment remains supportive for the next session.");
        } else if (newsSentiment.sentiment === "BEARISH") {
            contributors += 1;
            score.bearish += Math.max(4, Math.round((newsSentiment.confidence || 0) / 18));
            reasoning.push("News sentiment is adding downside caution for tomorrow.");
        } else {
            score.sideways += 4;
        }

        if (overallSignal.signal === "WAIT") {
            score.sideways += 8;
        }

        const verdict = buildVerdict(score, contributors, warnings, config);
        const support = pickFirstFinite(levels.nearestSupport, values.support);
        const resistance = pickFirstFinite(levels.nearestResistance, values.resistance);

        return {
            available: true,
            generatedAt: new Date().toISOString(),
            autoGenerated: Boolean(options && options.autoGenerated),
            tomorrowPrediction: {
                bias: verdict.bias,
                strength: verdict.strength,
                gapExpectation: verdict.gapExpectation,
                confidence: verdict.confidence,
                keyLevels: {
                    support: Number.isFinite(support) ? Utils.round(support, 2) : null,
                    resistance: Number.isFinite(resistance) ? Utils.round(resistance, 2) : null
                },
                strategy: buildStrategy(verdict.bias, support, resistance),
                holdAdvice: buildHoldAdvice(verdict.bias, verdict.strength),
                reasoning: Utils.pickSummaryReasoning(reasoning.concat(warnings), 8)
            }
        };
    }

    function shouldAutoGenerate(settings, now) {
        if (settings && settings.enablePostMarketAutoPrediction === false) {
            return false;
        }

        const parts = getIstParts(now || new Date());
        return (parts.hour * 60) + parts.minute >= (15 * 60) + 30;
    }

    function getIstParts(dateValue) {
        const formatter = new Intl.DateTimeFormat("en-CA", {
            timeZone: "Asia/Kolkata",
            hour12: false,
            year: "numeric",
            month: "2-digit",
            day: "2-digit",
            hour: "2-digit",
            minute: "2-digit"
        });
        const parts = formatter.formatToParts(dateValue instanceof Date ? dateValue : new Date(dateValue));
        const map = {};
        parts.forEach((part) => {
            map[part.type] = part.value;
        });
        return {
            year: Number(map.year),
            month: Number(map.month),
            day: Number(map.day),
            hour: Number(map.hour),
            minute: Number(map.minute)
        };
    }

    function evaluateCloseStrength(values) {
        const high = Utils.toNumber(values.dayHigh);
        const low = Utils.toNumber(values.dayLow);
        const close = Utils.toNumber(values.spotPrice);

        if (!Number.isFinite(high) || !Number.isFinite(low) || !Number.isFinite(close) || high <= low) {
            return {
                available: false,
                position: null
            };
        }

        return {
            available: true,
            position: (close - low) / (high - low)
        };
    }

    function calculateLastHourMomentum(snapshotsByTab) {
        const tabIds = Object.keys(snapshotsByTab || {});
        const slopes = tabIds.map((tabId) => Context.calculateSlope(snapshotsByTab[tabId], 60, "spotPrice"))
            .filter(Number.isFinite);
        return Utils.averageNumbers(slopes);
    }

    function applyTrendAlignment(score, trendAnalysis, closeStrength, reasoning) {
        const shortSignal = String(trendAnalysis && trendAnalysis.bias15m && trendAnalysis.bias15m.signal || "SIDEWAYS").toUpperCase();
        const longSignal = String(trendAnalysis && trendAnalysis.bias1h && trendAnalysis.bias1h.signal || "SIDEWAYS").toUpperCase();

        if (Context.isBullishSignal(shortSignal) && Context.isBullishSignal(longSignal) && closeStrength.position >= 0.7) {
            score.bullish += 18;
            reasoning.push("15-minute and 1-hour trend aligned bullish with a strong close near the high.");
            return;
        }

        if (Context.isBearishSignal(shortSignal) && Context.isBearishSignal(longSignal) && closeStrength.position <= 0.3) {
            score.bearish += 18;
            reasoning.push("15-minute and 1-hour trend aligned bearish with a weak close near the low.");
            return;
        }

        if (Context.isBullishSignal(shortSignal) && Context.isBullishSignal(longSignal)) {
            score.bullish += 12;
            reasoning.push("15-minute and 1-hour trend remain aligned bullish.");
            return;
        }

        if (Context.isBearishSignal(shortSignal) && Context.isBearishSignal(longSignal)) {
            score.bearish += 12;
            reasoning.push("15-minute and 1-hour trend remain aligned bearish.");
            return;
        }

        score.sideways += 12;
        reasoning.push("Trend signals are mixed, so sideways trade is still possible.");
    }

    function applyClosePosition(score, closeStrength, reasoning) {
        if (!closeStrength.available) {
            return;
        }

        if (closeStrength.position >= 0.8) {
            score.bullish += 10;
            reasoning.push("Closing price finished very near the day high.");
            return;
        }

        if (closeStrength.position <= 0.2) {
            score.bearish += 10;
            reasoning.push("Closing price finished very near the day low.");
            return;
        }

        score.sideways += 6;
        reasoning.push("Closing price finished in the middle of the daily range.");
    }

    function applyStructure(score, structureAnalysis, reasoning) {
        if (!structureAnalysis) {
            return;
        }

        if (structureAnalysis.structure === "HH_HL" || structureAnalysis.trend === "BULLISH") {
            score.bullish += 8;
            reasoning.push("Structure still shows higher highs and higher lows.");
        } else if (structureAnalysis.structure === "LH_LL" || structureAnalysis.trend === "BEARISH") {
            score.bearish += 8;
            reasoning.push("Structure still shows lower highs and lower lows.");
        } else {
            score.sideways += 5;
        }
    }

    function applyGapRead(score, gapPrediction, reasoning) {
        const primary = String(gapPrediction && gapPrediction.primary || "UNKNOWN").toUpperCase();
        if (primary === "GAP_UP") {
            score.bullish += 7;
            reasoning.push("Gap engine still favors a higher open.");
        } else if (primary === "GAP_DOWN") {
            score.bearish += 7;
            reasoning.push("Gap engine still favors a weaker open.");
        } else {
            score.sideways += 4;
        }
    }

    function buildVerdict(score, contributors, warnings, settings) {
        const ranked = [
            { key: "BULLISH", value: score.bullish },
            { key: "BEARISH", value: score.bearish },
            { key: "SIDEWAYS", value: score.sideways }
        ].sort((left, right) => right.value - left.value);
        const spread = ranked[0].value - ranked[1].value;
        let confidence = Utils.clamp(Math.round((spread * 3.2) + (contributors * 4)), 0, 100);

        if (warnings.length) {
            confidence = Utils.clamp(confidence - (warnings.length * 8), 0, 100);
        }

        let bias = ranked[0].key;
        if (spread <= 5 || confidence < (settings.lowConfidenceThreshold || 35)) {
            bias = "SIDEWAYS";
        }

        return {
            bias: bias,
            strength: resolveStrength(confidence),
            gapExpectation: resolveGapExpectation(bias, ranked[0], ranked[1]),
            confidence: confidence
        };
    }

    function resolveStrength(confidence) {
        if (confidence >= 70) {
            return "STRONG";
        }
        if (confidence >= 45) {
            return "MODERATE";
        }
        return "WEAK";
    }

    function resolveGapExpectation(bias, top, second) {
        if (bias === "BULLISH" && top.value - second.value >= 4) {
            return "GAP_UP";
        }
        if (bias === "BEARISH" && top.value - second.value >= 4) {
            return "GAP_DOWN";
        }
        return "FLAT";
    }

    function buildStrategy(bias, support, resistance) {
        const formattedSupport = Number.isFinite(support) ? Utils.formatNumber(support, 2) : "support";
        const formattedResistance = Number.isFinite(resistance) ? Utils.formatNumber(resistance, 2) : "resistance";

        if (bias === "BULLISH") {
            return {
                openPlan: `Favor CE setups if the open holds above ${formattedSupport} and does not fade immediately.`,
                breakoutPlan: `Above ${formattedResistance}, look for continuation and CE follow-through.`,
                breakdownPlan: `If price slips below ${formattedSupport}, step back and avoid fresh CE entries.`
            };
        }

        if (bias === "BEARISH") {
            return {
                openPlan: `Favor PE setups if the open stays below ${formattedResistance} and weakness persists.`,
                breakoutPlan: `If price reclaims ${formattedResistance}, avoid chasing PE entries.`,
                breakdownPlan: `Below ${formattedSupport}, look for PE continuation and breakdown follow-through.`
            };
        }

        return {
            openPlan: `Treat the open as range-bound unless price decisively moves away from ${formattedSupport} / ${formattedResistance}.`,
            breakoutPlan: `Only take CE continuation above ${formattedResistance} with volume confirmation.`,
            breakdownPlan: `Only take PE continuation below ${formattedSupport} with fresh weakness.`
        };
    }

    function buildHoldAdvice(bias, strength) {
        if (bias === "BULLISH") {
            return {
                CE: strength === "WEAK" ? "AVOID" : "HOLD",
                PE: "EXIT"
            };
        }

        if (bias === "BEARISH") {
            return {
                CE: "EXIT",
                PE: strength === "WEAK" ? "AVOID" : "HOLD"
            };
        }

        return {
            CE: "AVOID",
            PE: "AVOID"
        };
    }

    function pickFirstFinite() {
        for (let index = 0; index < arguments.length; index += 1) {
            if (Number.isFinite(arguments[index])) {
                return arguments[index];
            }
        }
        return null;
    }

    global.OptionsPostMarketEngine = {
        evaluate: evaluate,
        getIstParts: getIstParts,
        shouldAutoGenerate: shouldAutoGenerate
    };
})(typeof globalThis !== "undefined" ? globalThis : this);
